# Generated by Django 5.1.7 on 2025-03-30 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0002_disponibilidadehorarios_reuniao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisponibilidadeHorarios',
            new_name='DisponibilidadeHorario',
        ),
    ]
