# Generated by Django 5.1.7 on 2025-03-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0003_rename_disponibilidadehorarios_disponibilidadehorario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name_plural': 'reunioes'},
        ),
        migrations.AddField(
            model_name='mentorado',
            name='token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
